"""empty message

Revision ID: 3becabd36cd2
Revises: f1da3dac58f4
Create Date: 2026-01-17 15:49:29.293893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3becabd36cd2'
down_revision = 'f1da3dac58f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_chart', sa.String(length=128), nullable=True))
        batch_op.alter_column('first_pic',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('sec_pic',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('third_pic',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('fourth_pic',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('fourth_pic',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('third_pic',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('sec_pic',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('first_pic',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('size_chart')

    # ### end Alembic commands ###
